[project]
name = "roof-crack-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentations>=1.4.24",
    "findcrack>=0.1.5",
    "pillow>=12.3.0",
    "pyside6>=6.11.1",
    "pyside6-fluent-widgets>=1.11.2",
]

[tool.uv.sources]
findcrack = { path = "../findcrack", editable = true }
